backend:
  name: git-gateway
  branch: main


media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"


collections:
  - name: "insights"
    label: "Insights"
    folder: "src/content/insights"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Beschrijving", name: "description", widget: "text", required: false }
      - { label: "Datum", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
      - { label: "Update datum", name: "updated", widget: "datetime", required: false, format: "YYYY-MM-DD", time_format: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }

      - label: "SEO afbeelding"
        name: "image"
        widget: "object"
        required: false
        fields:
          - { label: "Afbeelding", name: "src", widget: "image", required: false }
          - { label: "Alt tekst", name: "alt", widget: "string", required: false }

      - { label: "Categorie", name: "category", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Leestijd", name: "readingTime", widget: "string", required: false, hint: "Bijv: 6 min" }

      - { label: "Content", name: "body", widget: "markdown" }
